### ISSUE TITLE
not previewing correctly on social media

### ISSUE THREAD

**Issue by warengonzaga** [web3phl/directory#48] opened 2022-08-21 03:45 UTC
### 🤔 Not Existing Bug?

- [X] Yes, I'm sure that this is a bug!

### 👀 Current Behavior

Not previewing to social media when shared.

### 🎯 Expected Behavior

It should have a preview when shared on social media.

### 📋 Steps To Reproduce

1. Copy-paste the URL to any social media
2. It will not show any preview
3. Done

### 📜 Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/web3phl/directory/blob/main/CODE_OF_CONDUCT.md).

**Comment by warengonzaga** [comment] 2022-08-21 03:48
The idea is that it does not have Metadata/Opengraph in the header of the homepage.
Learn more here: https://ogp.me

It should be easy to generate here.
https://www.opengraph.xyz

**Comment by kquirapas** [comment] 2022-08-21 04:56
Ill take this

**Comment by warengonzaga** [comment] 2022-08-21 05:09
Push the updates to #35 @kquirapas

**Comment by jnebab** [comment] 2022-08-21 16:52
is this fixed? I checked it in twitter card validator and there seems to be issue on the card preview but meta tags are all good. 
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/6265768/185802102-38121221-055e-456f-9e76-2e02b487c5c8.png">

**Comment by kquirapas** [comment] 2022-08-21 17:11
@jnebab I always use manual image so im curious what do you mean by this in Seo.tsx and how does opengraph do it?

```javascript
const defaultMeta = {
  // CODE SNIPPED
  /**
   * No need to be filled, will be populated with openGraph function
   * If you wish to use a normal image, just specify the path below
   */
  image: "",
};

```

Would it work better if we instead use a normal image?

**Comment by jnebab** [comment] 2022-08-22 03:33
> @jnebab I always use manual image so im curious what do you mean by this in `Seo.tsx` and how does opengraph do it?
> 
> ```js
> const defaultMeta = {
>   // CODE SNIPPED
>   /**
>    * No need to be filled, will be populated with openGraph function
>    * If you wish to use a normal image, just specify the path below
>    */
>   image: "",
> };
> ```
> 
> Would it work better if we instead use a normal image?

ahhh. this should be manually populated with an image URL since we dont have any images displayed on the homepage. opengraph is supposed to crawl for any image inside the link, but since we do not have any, it can't automatically generate a preview.

**Comment by warengonzaga** [comment] 2022-08-22 06:34
> > @jnebab I always use manual image so im curious what do you mean by this in `Seo.tsx` and how does opengraph do it?
> > ```js
> > const defaultMeta = {
> >   // CODE SNIPPED
> >   /**
> >    * No need to be filled, will be populated with openGraph function
> >    * If you wish to use a normal image, just specify the path below
> >    */
> >   image: "",
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Would it work better if we instead use a normal image?
> 
> yes. this should be manually populated with an image URL since we dont have any images displayed on the homepage. opengraph is supposed to crawl for any image inside the link, but since we do not have any, it can't automatically generate a preview.

Let's setup a default one instead, something like fallback.

**Comment by kquirapas** [comment] 2022-08-22 06:37
On it @warengonzaga I'll use this for now https://bafkreibpbviej7pxbkbhmzrhqeejjaunkhegmaokipsmqdptvpmkkhmima.ipfs.nftstorage.link/

**Comment by warengonzaga** [comment] 2022-08-22 06:42
> On it @warengonzaga I'll use this for now https://bafkreibpbviej7pxbkbhmzrhqeejjaunkhegmaokipsmqdptvpmkkhmima.ipfs.nftstorage.link/

That's is perfect!

**Comment by kquirapas** [comment] 2022-08-22 08:14
Pushed straight to dev: https://github.com/web3phl/directory/pull/35/commits/4ab9962213fd1371ad90f83420dbc64264c75dac

Let's close issue on confirmation of it working

**Comment by warengonzaga** [comment] 2022-08-22 08:21
Working as expected on dev branch. https://www.opengraph.xyz/url/https%3A%2F%2Fdirectory-dev.web3philippines.org

**Comment by kquirapas** [comment] 2022-08-22 08:27
Confirmed working.
![image](https://user-images.githubusercontent.com/85150796/185875565-de6bfb0d-ffcd-4ae9-8823-0ec9e19b6e07.png)

Closing issue

**Closed by kquirapas** 2022-08-22 08:27 UTC
Labels: bug, chore, waiting response
